### ISSUE TITLE
compiling with mingw

### ISSUE THREAD

**Issue by sonoro1234** [pac-dev/protoplug#10]
I would like to compile with mingw but I guess that (at least on windows) the compiler must be the same used compiling the vst-host to avoid run time libraries mismatches, and I guess that the standard is MSVC. Doing dependancy walker on Reaper dont show msvccrtxxx.dll so may be I could try.
What is your experience with this issue?

**Comment by pac-dev** [comment]
You could use **Visual Studio Express 2013 for Windows Desktop** or the older **Visual C++ 2010 Express**, which are free. 

I think having different C++ runtimes should not be a problem (it's a problem when memory is allocated with one runtime and freed with another, but this should never happen in a VST host/plugin relationship). 

As for the issue itself, someone else tried compiling protoplug with MinGW and said it failed at runtime, I think there are some small fixes to be done but it almost works.

**Comment by pac-dev** [comment]
For Windows I am now using the (free) VS2017 and it works fine. At this point, fixing compilation with MinGW does not seem like a sound time investment!
