### ISSUE TITLE
Can't Load libluajit on OSX Yosemete

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pac-dev/protoplug#16]
When I load Lua Protoplug FX into Apple's AU Lab, I see the following message in the log after telling it where the `ProtoplugFiles` are:

```
54:23 - Error: Could not load libluajit-5.1.so. Tried /Users/a/ProtoplugFiles/lib/libluajit-5.1.so and system path.
```

That file does exist, so I'm not quite sure what the problem would be. I'm a 64-bit OSX 10.10.5 system.

This may or may not be related to the other issue I'm having where Ardour refuses to recognize that Protoplug exists (same system). Despite clearing my AU cache and blacklist, and scanning multiple times (including after restarting Ardour), it still doesn't find it for some reason. If you want me to open a different issue for this (probably unrelated) problem, I can do that.

Protoplug looks very cool -- I'm looking forward to getting it working.

**Comment by pac-dev** [comment]
A bit late, but this was probably related to a broken release or the previously non-functioning 64-bit macOS build of LuaJIT. The latest macOS release is fully 64-bit and works fine in my testing.
