### ISSUE TITLE
Doesn't compile on Ubuntu Xenial

### ISSUE THREAD

**Issue by interstar** [pac-dev/protoplug#18]
Trying to compile from source on Ubuntu Xenial and I'm getting 

```
Compiling juce_core.cpp
../../../../Frameworks/JuceModules/juce_core/juce_core.cpp:116:110: note: #pragma message: "Please re-save your Introjucer project with the latest Introjucer version to avoid this warning"
 JUCE_COMPILER_WARNING ("Please re-save your Introjucer project with the latest Introjucer version to avoid this warning
                                                                                                             ^
In file included from ../../../../Frameworks/JuceModules/juce_core/juce_core.cpp:215:0:
../../../../Frameworks/JuceModules/juce_core/native/juce_linux_Files.cpp: In static member function ‘static bool juce::Process::openDocument(const juce::String&, const juce::String&)’:
../../../../Frameworks/JuceModules/juce_core/native/juce_linux_Files.cpp:203:44: error: expected ‘)’ before ‘...’ token
  if (URL::isProbablyAWebsiteURL (fileName) ... )
                                            ^
../../../../Frameworks/JuceModules/juce_core/native/juce_linux_Files.cpp:204:10: error: expected primary-expression before ‘||’ token
          || cmdString.startsWithIgnoreCase ("file:")
          ^
Makefile:202: recipe for target 'build/intermediate/Debug/juce_core_1a6f1539.o' failed
make[1]: *** [build/intermediate/Debug/juce_core_1a6f1539.o] Error 1
make[1]: Leaving directory '/media/phil/MyData/music_making_tools/protoplug/Builds/fx/Builds/Linux'
Makefile:7: recipe for target '../../../Bin/linux/Lua Protoplug Fx.so' failed
make: *** [../../../Bin/linux/Lua Protoplug Fx.so] Error 2

```

Any suggestions?

**Comment by pac-dev** [comment]
Well there's clearly an opening parenthesis missing on line 203. Not sure how the other toolchains even compiled that without errors! I'll push the fix but for now you can just add that opening parenthesis like this

`if ((URL::isProbablyAWebsiteURL...`

**Comment by interstar** [comment]
Thanks pac-dev.

Actually this was compiling directly from the Github repo. I then downloaded the release zip and WAS able to compile from there. I wonder if some automatic patching update of Juce introduced that error into the repo? (BTW : the autobuild link seems broken as well)

Anyway, I'm now trying to use Protoplug in Linux. 

I downloaded it pre-compiled in Windows, and it works beautifully in FL Studio. And I'm really excited by it (thank you for creating it) because there's a bunch of stuff which I've wanted to do as a plugin but never got my head around writing my own VSTs. Plus Lua is much nicer than C++. So, that's awesome.

But so far, I haven't got it working in Linux. 

I CAN load Protoplug into Ardour4, but it's just hanging with an error message "ProtoplugFiles not found!" which then hangs. If I click the "locate directory" button nothing seems to happen. I've copied the ProtoplugFiles directory into the Bin/linux directory so it's alongside the compiled .so files, but that doesn't seem to help.  So where should it actually be, for the plugins to find it? 

Are you, yourself, successfully using Protoplug in Linux? If so, what are you hosting it in?

cheers

Phil

**Comment by pac-dev** [comment]
- Hmm, you should be able to put the ProtoplugFiles directory anywhere and point to it on first run. I'll need to check if that happens in other DAWs. That being said the default Linux path is `/usr/share/ProtoplugFiles`. This is created automatically when you run `make install`. Which I realize isn't in the instructions, I should probably update those build instructions in the README to be something like this:
```
cd protoplug-1.3.0/Builds/multi/Linux
make
sudo make install
```

- I've successfully run the native Linux version in a few DAWs, but it was a while ago and I can't find my notes on the subject -_-. If I recall correctly, in Ardour the GUI wasn't working well anyways. I tried debugging but I couldn't figure it out. Worked perfectly in Carla (which doesn't really have a sequencer but I love playing with it) and I believe I successfully tested energyXT, Qtractor, and Bitwig. It should also work in Renoise and Tracktion but I don't think I tested those. You'll notice that these are nearly all commercial. Too bad LMMS doesn't support native linux VSTs. I think it handled the windows DLL semi-well but I should check again.
- Yeah the Linux prebuilt packages don't exist anymore :) If I do provide Linux binaries again, I will probably opt for something simpler like a deb and an rpm download. The Open Build Service was exceedingly complex for my use case, cool platform though.

Pierre

**Comment by interstar** [comment]
OK. Thanks again.

Yes, doing `sudo make install` definitely helped :-) 

(should have thought of it myself)

And yes, now it seems to load OK, but yes, UI is definitely broken.

It opens with the promising looking text editor, but then replaces it with a black window, and nothing seems to do anything more. 

![protoplug](https://user-images.githubusercontent.com/90998/28678129-f27746d8-72c5-11e7-82a7-c0df78ce1a7e.png)

**Comment by interstar** [comment]
Re: other hosts. 

I tried installing LMMS with VST support but the most recent instructions I found refered to files that were missing. I assume that VST support isn't a priority. What are the issues of making Protoplug as something that fits LMMS's own plugin format?

**Comment by pac-dev** [comment]
- I'll play with Ardour and the latest version of protoplug to see how it goes, then post results in the corresponding issue (#13).

- You probably already figured that out, but LMMS [does not support native linux VSTs](https://github.com/LMMS/lmms/issues/416). It does support Windows VSTs through Wine, so the best bet for LMMS is to run the windows version of protoplug in it.

Anyways the main issue is fixed I believe so I'll close this.
