### ISSUE TITLE
midi output/midi-chordify.lua demo not working in FLStudio 12

### ISSUE THREAD

**Issue by NoodleSushi** [pac-dev/protoplug#21]
![capture](https://user-images.githubusercontent.com/34954180/38160804-a26d72dc-34f5-11e8-9632-08a44926e7d5.PNG)
I have tried this in FLStudio 12 Patcher, with:
- green lines representing **midi data**
- yellow lines representing **audio data**

When I tried pressing the keyboard keys, there is no midi output from protoplug.
The **Chip32 Plugin** works when I directly send the midi input from FLStudio to itself.
I don't know if its just my software but protoplug's midi output doesn't work

**Comment by interstar** [comment]
Hmmm ... 
In FL Studio 12 I'm successfully sending MIDI from Protoplug to another VST synth by setting the protplug MIDI out channel to 2, and setting the MIDI in of the other synth to be channel 2.

That works OK.

This isn't using Patcher though. Maybe Patcher's way of handling MIDI is different somehow.

**Comment by pac-dev** [comment]
Nice screenshot :) Closing as MIDI output reportedly works in FL Studio 12 without Patcher, and in every DAW I've tried. Perhaps Patcher only runs the plugin when its audio output is somehow routed to the main audio out, possibly related to the fact that protoplug doesn't declare itself as a "MIDI effect plugin". Try connecting those. Feel free to comment/reopen if necessary.

**Comment by DominikStarke** [comment]
Cool Plugin!
On FL-Studio for Windows: It works in Patcher but you have to configure the VST-Wrapper output port:

![protoplug1](https://user-images.githubusercontent.com/5812061/70031829-7170d680-15ac-11ea-9d2f-b23fe0ea6767.png)
![protoplug2](https://user-images.githubusercontent.com/5812061/70031834-73d33080-15ac-11ea-86cd-c83eb3f8a6a6.png)

On FL-Studio for Mac: I couldn't get ProtoPlug to work directly inside Patcher. I had to use either rewire to load it to a nested FL Studio instance or (easier) load it into MiniHostModular (which was loaded as vst to Patcher)

**Comment by interstar** [comment]
By doing it the Input Port / Output Port way, I don't think Patcher is particularly relevant. The MIDI port routing is independent of the midi control routing you draw into Patcher
