### ISSUE TITLE
The link is down

### ISSUE THREAD

**Issue by yanterrien** [pac-dev/protoplug#22]
So... how to install on Iinux ? The given link is down:
https://software.opensuse.org/download.html?project=home%3Apac-dev&package=protoplug

**Comment by pac-dev** [comment]
Right, there was a broken link in the latest release for a while. The newer release should have no broken links. It provides Linux binaries in a different way: I have stopped using the OpenSUSE Build Service for Linux binaries (too much work), instead the release provides a direct download for binaries compiled on Ubuntu 16 (64-bit). These should also work on any system with libstdc++5. If they don't work you might have to compile it yourself following the instructions in the Readme.
