### ISSUE TITLE
FYI: Arch User Repository package for protoplug created

### ISSUE THREAD

**Issue by SpotlightKid** [pac-dev/protoplug#23]
Just an FYI for the developer: I created an Arch User Repository (AUR) a package for protoplug:

https://aur.archlinux.org/packages/protoplug/

Arch Linux users can install this by either downloading the `PKGBUILD` and using `makepkg`:

    $ sudo pacman -S curl git gtk3 luajit  # install required packages
    $ git clone https://aur.archlinux.org/protoplug.git
    $ cd protoplug
    $ makepkg -ci

or by using an AUR manager, like e.g. `aurman`:

    $ aurman -S protoplug

In the latter case all required dependencies will be installed automatically for you.

--- 

Feel free to close this issue after reading.

**Comment by pac-dev** [comment]
Nice to see you're still into this despite development slaking off for a while! Yea, I think having a couple of properly supported distros is more practical than the OpenSUSE Build Service that I used before, at least for a project like this. I will mention this package in the Readme / website / release.

**Comment by pac-dev** [comment]
Added a link in the [release](https://github.com/pac-dev/protoplug/releases). The Readme and website just have links to that for now but I do plan to complete the Readme with install instructions (and code samples, etc.)
