### ISSUE TITLE
host-synchronized midicontrolled gate + midi MTC commands

### ISSUE THREAD

**Issue by coderofsalvation** [pac-dev/protoplug#7]
I want to make the following linux plugin, and I would like to get some guidelines / feedback whether this is possible: 

(and if not this'll be the featurerequest):

* receive midi-in messages
* delay these midi-in messages a variable amount of ms
* send them to midi-out

and, at the same :

* receive `start`- and `stop`- events from pluginhost (JACK transport?)
* and send as [MMC](http://en.wikipedia.org/wiki/MIDI_Machine_Control) midi `start`- and `stop`- bytes to midi-out

so practically I need to send these raw midi-bytes:

     start MMC bytes: 0xF0 0x7F 0x7F 0x06 0x02
     stop  MMC bytes: 0xF0 0x7F 0x7F 0x06 0x01

**Comment by SpotlightKid** [comment]
Towards your first question, the genaral strategy would be:

* get the sample rate
* calculate your delay length in terms of samples and numbers of buffer periods
* read the midi events and store them together with a timestamp (e.g. samples since startup)
* in each period, check if the delay numer of buffer periods and samples has passed,
* comparing the actual  and, if yes
* add the stored midi events to the output buffer

**Comment by coderofsalvation** [comment]
I think I already got the midimsg delay working (I looked at the midiChordify example):

    require "include/protoplug"

    local mididelay
    local delayBuf = {}
    local playing = false

    function plugin.processBlock(samples, smax, midiBuf)
      blockEvents = {}
      -- analyse midi buffer and prepare a chord for each note
      for ev in midiBuf:eachEvent() do
        ev.time = ev.time + mididelay
        table.insert( delayBuf, ev )    
      end
      -- fill midi buffer with delayed notes
      midiBuf:clear()
      sendDelayBuf(midiBuf)
      
    end

    function sendDelayBuf(midiBuf)
      if #delayBuf>0 then
        for _,e in ipairs(delayBuf) do
          if e.time < smax then       
            midiBuf:addEvent(e)
            table.remove( delayBuf, _ )
            print "midi msg!"
          else
            e.time = e.time - smax
          end
        end
      end
    end

    function sendMMC()
      if not playing and plugin.PositionInfo.isPlaying
        -- send start to midi out ( 0xF0 0x7F 0x7F 0x06 0x02 )
      end
      if playing and not plugin.PositionInfo.isPlaying
        -- send stop to midi out ( 0xF0 0x7F 0x7F 0x06 0x01 )
      end   
    end 

    params = plugin.manageParams {
      {
        name = "Mididelay";
        type = "int";
        max = 50000;
        changed = function(val) mididelay = val end;
      }
    }

Now I only need to send out the midi bytes by creating some custom midi events.
WDYT?

**Comment by pac-dev** [comment]
For receiving start and stop events from the host, you can use plugin.getCurrentPosition().isPlaying. Here's an example:
```
require "include/protoplug"

local oldPlaying = false

function plugin.processBlock(samples, smax, midiBuf)
	local info = plugin.getCurrentPosition()
	if info and info.isPlaying ~= oldPlaying then
		print (info.isPlaying and "Host started playing!" or "Host stopped!")
		oldPlaying = info.isPlaying
	end
end
```
For sending custom MIDI messages, the API docs are pretty explicit, there's even an example!:

http://www.osar.fr/protoplug/api/modules/midi.html#midi.Event:Event

**Comment by coderofsalvation** [comment]
indeed nothing wrong with those docs!
thnx
